server:
  port: 8080
#  port: ${PORT:8080}

spring:
  application:
    name: SakuraSaki

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/sakura_saki?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Colombo}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:#0507cjchanu}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  thymeleaf:
    cache: false
