server:
  port: 8080

spring:
  application:
    name: SakuraSaki

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://sakura-saki-sakura-saki-8f40.h.aivencloud.com:26530/defaultdb?sslMode=REQUIRED}
    username: ${SPRING_DATASOURCE_USERNAME:avnadmin}
    password: ${SPRING_DATASOURCE_PASSWORD:AVNS_dDB2Ptw4NTfc_MUy5CZ}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  thymeleaf:
    cache: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
